import { Category, Product } from '../../shared/types.js';
export const CATEGORIES: Category[] = [
  {
    id: 'do-an-vat',
    name: 'Đồ Ăn Vặt',
    icon: 'fa-solid fa-cookie-bite',
    subcategories: [
      { id: 'snack', name: 'Snack & Bim Bim', categoryId: 'do-an-vat' },
      { id: 'banh-keo', name: 'Bánh Kẹo', categoryId: 'do-an-vat' },
      { id: 'hat-say', name: 'Các Loại Hạt', categoryId: 'do-an-vat' },
      { id: 'trai-cay-say', name: 'Trái Cây Sấy', categoryId: 'do-an-vat' },
    ],
  },
  {
    id: 'thuc-pham-che-bien',
    name: 'Thực Phẩm Chế Biến',
    icon: 'fa-solid fa-utensils',
    subcategories: [
      { id: 'do-hop', name: 'Đồ Hộp', categoryId: 'thuc-pham-che-bien' },
      { id: 'mi-an-lien', name: 'Mì Ăn Liền', categoryId: 'thuc-pham-che-bien' },
      { id: 'gia-vi', name: 'Gia Vị & Sốt', categoryId: 'thuc-pham-che-bien' },
      { id: 'thuc-pham-dong-lanh', name: 'Thực Phẩm Đông Lạnh', categoryId: 'thuc-pham-che-bien' },
    ],
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'snack-1',
    name: "Bim Bim Khoai Tây Lay's Vị Tự Nhiên",
    price: 12000,
    imageUrl: 'https://picsum.photos/seed/lays/400/400',
    subcategoryId: 'snack',
    description: 'Giòn tan, thơm ngon, hương vị khoai tây nguyên bản.',
  },
  {
    id: 'snack-2',
    name: 'Snack Mực Lăn Bơ Tỏi Poca',
    price: 15000,
    imageUrl: 'https://picsum.photos/seed/poca/400/400',
    subcategoryId: 'snack',
    description: 'Hương vị biển cả kết hợp bơ tỏi thơm lừng.',
  },
  {
    id: 'banh-keo-1',
    name: 'Bánh Choco-pie Hộp 12 Cái',
    price: 55000,
    imageUrl: 'https://picsum.photos/seed/chocopie/400/400',
    subcategoryId: 'banh-keo',
    description: 'Vỏ bánh mềm xốp, nhân marshmallow dẻo dai.',
  },
  {
    id: 'banh-keo-2',
    name: 'Kẹo Dẻo Gummy Bear Haribo',
    price: 45000,
    imageUrl: 'https://picsum.photos/seed/haribo/400/400',
    subcategoryId: 'banh-keo',
    description: 'Kẹo dẻo hình gấu đủ vị trái cây.',
  },
  {
    id: 'hat-say-1',
    name: 'Hạt Điều Rang Muối Bazan',
    price: 150000,
    imageUrl: 'https://picsum.photos/seed/cashew/400/400',
    subcategoryId: 'hat-say',
    description: 'Hạt điều to, béo ngậy, rang muối đậm đà.',
  },
  {
    id: 'trai-cay-say-1',
    name: 'Mít Sấy Giòn Vinamit',
    price: 60000,
    imageUrl: 'https://picsum.photos/seed/vinamit/400/400',
    subcategoryId: 'trai-cay-say',
    description: 'Mít sấy giữ trọn vị ngọt tự nhiên, giòn rụm.',
  },
  {
    id: 'do-hop-1',
    name: 'Cá Ngừ Ngâm Dầu Vissan',
    price: 25000,
    imageUrl: 'https://picsum.photos/seed/vissan/400/400',
    subcategoryId: 'do-hop',
    description: 'Thịt cá ngừ săn chắc, ngâm dầu thực vật béo ngậy.',
  },
  {
    id: 'do-hop-2',
    name: 'Pate Gan Hạ Long',
    price: 22000,
    imageUrl: 'https://picsum.photos/seed/halong/400/400',
    subcategoryId: 'do-hop',
    description: 'Pate gan truyền thống, hương vị thơm ngon đặc trưng.',
  },
  {
    id: 'mi-an-lien-1',
    name: 'Mì Hảo Hảo Tôm Chua Cay',
    price: 4500,
    imageUrl: 'https://picsum.photos/seed/haohao/400/400',
    subcategoryId: 'mi-an-lien',
    description: 'Sợi mì dai, nước súp chua cay đậm đà, chuẩn vị Việt.',
  },
  {
    id: 'mi-an-lien-2',
    name: 'Mì Trộn Indomie Mi Goreng',
    price: 6000,
    imageUrl: 'https://picsum.photos/seed/indomie/400/400',
    subcategoryId: 'mi-an-lien',
    description: 'Mì xào khô nổi tiếng của Indonesia, thơm ngon khó cưỡng.',
  },
  {
    id: 'gia-vi-1',
    name: 'Tương Ớt Chinsu',
    price: 15000,
    imageUrl: 'https://picsum.photos/seed/chinsu/400/400',
    subcategoryId: 'gia-vi',
    description: 'Vị cay nồng, màu sắc hấp dẫn, hợp với mọi món ăn.',
  },
  {
    id: 'thuc-pham-dong-lanh-1',
    name: 'Chả Giò Cầu Tre',
    price: 70000,
    imageUrl: 'https://picsum.photos/seed/cautre/400/400',
    subcategoryId: 'thuc-pham-dong-lanh',
    description: 'Vỏ giòn rụm, nhân đầy đặn, tiện lợi cho bữa ăn gia đình.',
  },
];
